# Generated by Django 4.0.1 on 2022-02-26 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_shopuser_activation_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
                ('gender', models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский'), ('NON_BINARY', 'Другой')], max_length=10, verbose_name='Гендер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
