# Generated by Django 4.0.1 on 2022-03-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ia_active',
            new_name='is_active',
        ),
    ]
