# Generated by Django 4.0.1 on 2022-03-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_rename_ia_active_order_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_process', 'в обработке'), ('created', 'создан'), ('canceled', 'отменен'), ('paid', 'оплачен'), ('ready', 'готов к выдаче'), ('received', 'получен'), ('awaiting payment', 'ждет оплаты')], default='created', max_length=20, verbose_name='статус заказа'),
        ),
    ]
