# Generated by Django 4.0.1 on 2022-01-27 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=128, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='Описание')),
                ('color', models.CharField(choices=[('не указан', 'не указан'), ('черный', 'черный'), ('красный', 'красный'), ('синий', 'синий'), ('желтый', 'желтый')], default='не указан', max_length=10, verbose_name='Цвет')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productcategory')),
            ],
        ),
    ]
